module.exports={
    entry:'./main.js',
    output:{
        filename:'bundle.js'
    },
    module:{
        rules:[
            {
                test:/\.js[x]?$/,
                use:{
                    loader:'babel-loader',
                    options:{
                        presets:['es2015','react']
                    }
                },
                exclude:/node_modules/
            }
        ]
    }
}